name: zarr-demo
channels:
- conda-forge
- anaconda
dependencies:
- dask
- gcsfs
- geopandas
- h5netcdf
- icechunk
- ipython
- ipykernel
- jupyter
- matplotlib
- notebook
- numpy
- pandas
- pyarrow
- pyogrio
- pyproj
- python>=3.12
- rasterio
- rioxarray
- shapely
- virtualizarr
- xarray
- xproj
- zarr
- pip:
  - topozarr
