name: zarr-demo
channels:
- conda-forge
- anaconda
dependencies:
- dask
- icechunk
- ipython
- ipykernel
- jupyter
- matplotlib
- ndpyramid
- notebook
- numpy
- pandas
- pip
- pre_commit
- python>=3.12
- rasterio
- virtualizarr
- xarray
- xproj
- zarr
- pip:
  - topozarr
